// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel POIAnalysis

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
Texture2D<int> AnalysisImage;
RWStructuredBuffer<int> AnalysisImageBuffer;

[numthreads(8,8,1)]
void POIAnalysis (uint3 id : SV_DispatchThreadID)
{
	float width, height;
	AnalysisImage.GetDimensions(width, height);
	AnalysisImageBuffer[id.y * width + id.x] = AnalysisImage[id.xy];
}
